require 'rubygems'
require 'sinatra'
# Generated by cucumber-sinatra. (Sat Mar 19 20:31:00 +0100 2011)
ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec/expectations'
require 'rack/test'

Capybara.app = KrokenSlide

class KrokenSlideWorld
	include Rack::Test::Methods
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
	def app
		Sinatra::Application
	end
end

World do
  KrokenSlideWorld.new
end
